import 'package:flutter/material.dart';
import 'package:webview_flutter/webview_flutter.dart';
void main(){WidgetsFlutterBinding.ensureInitialized();runApp(const AuraApp());}
class AuraApp extends StatelessWidget{const AuraApp({super.key});
@override Widget build(BuildContext c)=>MaterialApp(debugShowCheckedModeBanner:false,home:const AuraView());}
class AuraView extends StatefulWidget{const AuraView({super.key});
@override State<AuraView> createState()=>_S();}
class _S extends State<AuraView>{
late final WebViewController _c;
final String _h='The provided code snippet contains only the initial HTML structure and CSS styling for the "تطبيق منبه" application. It is incomplete and does not include the core HTML elements for user interaction (e.g., time input, alarm list) or any JavaScript logic for setting, managing, or triggering alarms.\n\nTherefore, a full audit for logic errors, security, and performance of the *entire application* cannot be performed at this time.\n\n**Audit of the Provided Snippet (HTML & CSS):**\n\nThe HTML and CSS provided are of excellent quality and demonstrate strong adherence to modern web development best practices:\n\n*   **HTML Structure:**\n    *   Correct `<!DOCTYPE html>` and `lang="ar" dir="rtl"` for Arabic and RTL support.\n    *   Proper use of `<meta charset="UTF-8">` and `<meta name="viewport">`.\n    *   Clear and descriptive `<title>`.\n*   **CSS Styling:**\n    *   **CSS Variables (`:root`):** Well-defined, descriptive, and effectively used for a consistent and easily maintainable theme.\n    *   **Universal Reset (`*`):** `box-sizing: border-box; margin: 0; padding: 0;` is a solid foundation for consistent layouts.\n    *   **`body` Styles:**\n        *   Uses modern Flexbox for perfect centering (`display: flex`, `justify-content`, `align-items`).\n        *   `min-height: 100vh` ensures the content is centered even on short pages.\n        *   `overflow: hidden` is a good practice for background canvases to prevent unwanted scrollbars.\n        *   `font-size: 16px` provides a good base for accessibility.\n    *   **`#particle-canvas`:** Correctly positioned as a full-screen background with `z-index: 0`.\n    *   **`.container` (Glassmorphism):**\n        *   Implements the glassmorphism effect flawlessly with `background`, `border`, `backdrop-filter`, and `-webkit-backdrop-filter`.\n        *   `box-shadow` creates a visually appealing neon glow and depth.\n        *   Responsive design with `width: 90%` and `max-width: 500px`.\n        *   `text-align: right` is correctly applied for RTL.\n        *   Uses Flexbox (`display: flex`, `flex-direction: column`, `gap`) for efficient internal layout.\n\n**Conclusion for the Provided Snippet:**\n\nThe HTML and CSS in this snippet are **perfect** within their scope. They are clean, well-organized, responsive, accessible (for RTL), and visually appealing. There are no discernible logic errors, security vulnerabilities, or performance issues in this specific part of the code.\n\n**However, to provide a complete audit for the "تطبيق منبه" application, the full HTML (including input fields, alarm list, etc.) and all JavaScript logic are required.**\n\nPlease provide the complete code for a comprehensive audit.';
@override void initState(){super.initState();_c=WebViewController()..setJavaScriptMode(JavaScriptMode.unrestricted)..loadHtmlString(_h);}
@override Widget build(BuildContext c)=>Scaffold(body:SafeArea(child:WebViewWidget(controller:_c)));}