import 'package:flutter/material.dart';
import 'package:webview_flutter/webview_flutter.dart';
void main(){WidgetsFlutterBinding.ensureInitialized();runApp(const AuraApp());}
class AuraApp extends StatelessWidget{const AuraApp({super.key});
@override Widget build(BuildContext c)=>MaterialApp(debugShowCheckedModeBanner:false,home:const AuraView());}
class AuraView extends StatefulWidget{const AuraView({super.key});
@override State<AuraView> createState()=>_S();}
class _S extends State<AuraView>{
late final WebViewController _c;
final String _h='<!DOCTYPE html>\n<html lang="ar" dir="rtl">\n<head>\n    <meta charset="UTF-8">\n    <meta name="viewport" content="width=device-width, initial-scale=1.0">\n    <title>منبه - Cyberpunk Alarm</title>\n    <!-- Google Fonts: Orbitron for display, Cairo for body text (Arabic friendly) -->\n    <link href="https://fonts.googleapis.com/css2?family=Orbitron:wght@400;700&family=Cairo:wght@400;700&display=swap" rel="stylesheet">\n    <style>\n        /* Root Variables for Cyberpunk Theme */\n        :root {\n            --color-bg-dark: #0a0a0e; /* Deep dark background */\n            --color-bg-medium: #1a1a2e; /* Slightly lighter for panels */\n            --color-bg-light: #2a2a4a; /* Even lighter for inputs/toggles */\n            --color-neon-blue: #00f0ff; /* Primary accent */\n            --color-neon-purple: #8a2be2; /* Secondary accent */\n            --color-neon-green: #39ff14; /* Success/active state */\n            --color-neon-red: #ff073a; /* Danger/alarm state */\n        }\n        /* Add more styles here as needed for the alarm clock components */\n        body {\n            font-family: \'Cairo\', sans-serif;\n            background-color: var(--color-bg-dark);\n            color: var(--color-neon-blue);\n            margin: 0;\n            display: flex;\n            justify-content: center;\n            align-items: center;\n            min-height: 100vh;\n            overflow: hidden;\n            flex-direction: column;\n            text-align: center;\n        }\n\n        .container {\n            background-color: var(--color-bg-medium);\n            border: 2px solid var(--color-neon-blue);\n            box-shadow: 0 0 20px var(--color-neon-blue), 0 0 30px var(--color-neon-purple) inset;\n            padding: 40px;\n            border-radius: 15px;\n            display: flex;\n            flex-direction: column;\n            gap: 25px;\n            max-width: 500px;\n            width: 90%;\n            position: relative;\n            z-index: 1;\n        }\n\n        h1 {\n            font-family: \'Orbitron\', sans-serif; /* Corrected: \'font-famil\' was incomplete */\n            color: var(--color-neon-green);\n            text-shadow: 0 0 10px var(--color-neon-green), 0 0 20px var(--color-neon-purple);\n            font-size: 2.5em;\n            margin-bottom: 20px;\n            letter-spacing: 2px;\n        }\n    </style>\n</head>\n<body>\n    <div class="container">\n        <h1>منبه - Cyberpunk Alarm</h1>\n        <!-- Further alarm clock components would go here -->\n        <p>This is a placeholder for the alarm clock functionality.</p>\n    </div>\n</body>\n</html>';
@override void initState(){super.initState();_c=WebViewController()..setJavaScriptMode(JavaScriptMode.unrestricted)..loadHtmlString(_h);}
@override Widget build(BuildContext c)=>Scaffold(body:SafeArea(child:WebViewWidget(controller:_c)));}